/**
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.scoping;

import uam.extremo.casestudy.epmltext.scoping.AbstractEPMLTextScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class EPMLTextScopeProvider extends AbstractEPMLTextScopeProvider {
}
