/**
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.validation;

import uam.extremo.casestudy.epmltext.validation.AbstractEPMLTextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EPMLTextValidator extends AbstractEPMLTextValidator {
}
