os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8


deploy:
  provider: releases

  user:
    secure: bcnUwtAwsq3cqxXpwfYkHrdzClbheqE79oThEULJLuKJox87Ml5TdSlxikPk28+yCyYcm3ZSTWD1epCYL8bQXZJDNAb+1Dj/ecoVENQGTfpJZruG5/KDiIjRBhdkcl8BzQ84SlOFq5XlMSxKbrHys1VfqQFuIGn3s8u3gPcjtqIknEVPdSZIcLQDVkb6rWnf8zR5h7yhf4LZQvXEMy91cKXnT0q9tI6UW4W4Y8SkNFEuYz3YgX+2O0ANIU3PbEciH4ZGnfiUKIyN/y+FNiYkJ1ZlorcF56sy5yQcuoI2dClFPBIYT9Wr4IX1ddnwmX4bOw6E3F+19uDgWpjVhwOpBehYcWDy9ITCrMWoIkNk3VJyRgxZ2hAFZWIcq42vZ2SeHQPutGngV1XX+qiCP/JlGTwB+mieLAqOpyEiXmw+9GFpfQHtQdGU0h3KcY+MGhwoLgEb0K8JqotSWsZU2EOGiaSOfK0sboL49tEDMu4IYB/m45zJeJfQQooC0dRxS3eoMRfCwSDNHhz45Hg2OIw7S+T0c1eIPdEEJUWoeTz61HAnXEJM0xxvkolR9cidAYSHq1cvulnm3/Kb/MNoldcyC/MTgc2ju99ciaJlydvYsu6mLhDnqgR+O43sCdHDSeSiaUMz8eBM4/KsWFvpLClxNRrIJEt/Xg4wQqgG2nBI6qo=
  password:
    secure: XUvPIu4mm8PgW6qHE2oDIPRJEkjJZ5Mcb4ambyiB7KuppnF/LdbhMcX6kFSIuPYDYJ9LdiVtLvY7LjyWjSo5bcbc/8KZFf7a9g9TNbQGov/hIZmq/8fsuy6p/39j0/TBe8MMNEHPiOH5hJxYkkPllVxL3Na/wyPgiiXA73oP3aRoLKA9Hyx2ei6PqkDBPD0KXzqn8pBIiZam3mYuf3rYcJAYgnn8CDmEXYZXHh7cFWnyd/yQjNqmfRIPwygBXyO3nYKI56a3d6NTmmAEUJ1AvNfpsWX5qX9XVmuS5COtsoDLGm7+GyGVmFG+uaq5EfpMbL7HtLj1VtK83SQFG7fAB3vtpTACQhp6dYPXICAuSxcfgM2Ty8PuxhoV7T635B35SrO48FvQv4u7z/V1KLiX9ftAfUu26IYMpV4/TUr3dNixWK8KQv6/4Y33gdXGvJn5XELUOWtKJSugFPFnbmFLoDUR1FhNI6VOVR2MeNXShrhiZQbAHbMnTNXYYR/byNRKcsSjyMbIJmnZxCrT4dFtTnHih56ZJfYi8N8zNr0mLEz6LzIqkpwHbmIXaiZIRXDNTyKgwlHaFiGy5saQQotYnGrNI6t4yJdJj6bPo3ijZbqpENJfDlnGcBVqWu5er3pO+mtAq9FVzS7VuZmeSFq3dMRCag/PpjFcfdCEFCCD2Xc=
  api_key:
    secure: U4mEdqnpo1ohVgQnu9fVoM2vQcnV37eo96rPSfiBy/x+LxRT9EbI8Ua785h/fMucY3Z9JzJn+CGTktTNlMjbqb0cspv6FlScmJO8clz/X4Ml3n9kYP7ipfFbBnvTCZqFz2xK5qy4hwPNG0Q+1RAiGowBQ4fP8KJ1Fh3tGGWvsZIwnUhbYw4F9+5RGPBc76RjHfbe0aRB9jRAaJxKMSOXv0jNON1nlmK+IQRta8//bshLlfFK25AVQQ2hBV1WIlw011xpnK5rplgaKT49LTjRwE6nzb/o3i1SByCQgVXR11CO+fOZFsf6K77/mf0aiM1JwCidhZNiOqapglUs5SsUpNvWQ6LXw/74HAMClYGHApptaIQwdenKeZCRMJsDiyeVNHD2qdlwmdse7M19Rux1F0mIHtUTvWnsWfr6THg5zlgkUtc5vx/lxX/+wbHdyQuyA+7n4EdjyANtJ6zANrsLQWjPfQ/QkuvnYpjM3enL+ZDEM+PFcoyBtL2hQfNn9i6lherHEK7qH+PxcDrCYuTl/40Fv9aCRsfWMdM91rOUQxY7qR3k3eMUDMrYZeCsp2CCDclTmyOmwuSOnj8FFE5areXJVb3Fd5yPN4sFox05FVi/+2FkigbSVixdlqAVUAxZdycXzAgSmq6UiPFaKjMj1e3b5N+C/7ReivONTOWfx7k=
  
  skip_cleanup:
    true
  file:
    update-site
  on:
    tags: true
  
