before_install:
    - openssl aes-256-cbc -K $encrypted_46d5efca5ac9_key -iv $encrypted_46d5efca5ac9_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar

install:
    - mvn --settings settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script: 
    - mvn clean deploy --settings settings.xml -DskipTests=true -B -U -Prelease
