os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: U4mEdqnpo1ohVgQnu9fVoM2vQcnV37eo96rPSfiBy/x+LxRT9EbI8Ua785h/fMucY3Z9JzJn+CGTktTNlMjbqb0cspv6FlScmJO8clz/X4Ml3n9kYP7ipfFbBnvTCZqFz2xK5qy4hwPNG0Q+1RAiGowBQ4fP8KJ1Fh3tGGWvsZIwnUhbYw4F9+5RGPBc76RjHfbe0aRB9jRAaJxKMSOXv0jNON1nlmK+IQRta8//bshLlfFK25AVQQ2hBV1WIlw011xpnK5rplgaKT49LTjRwE6nzb/o3i1SByCQgVXR11CO+fOZFsf6K77/mf0aiM1JwCidhZNiOqapglUs5SsUpNvWQ6LXw/74HAMClYGHApptaIQwdenKeZCRMJsDiyeVNHD2qdlwmdse7M19Rux1F0mIHtUTvWnsWfr6THg5zlgkUtc5vx/lxX/+wbHdyQuyA+7n4EdjyANtJ6zANrsLQWjPfQ/QkuvnYpjM3enL+ZDEM+PFcoyBtL2hQfNn9i6lherHEK7qH+PxcDrCYuTl/40Fv9aCRsfWMdM91rOUQxY7qR3k3eMUDMrYZeCsp2CCDclTmyOmwuSOnj8FFE5areXJVb3Fd5yPN4sFox05FVi/+2FkigbSVixdlqAVUAxZdycXzAgSmq6UiPFaKjMj1e3b5N+C/7ReivONTOWfx7k=
  file: update-site
  on:
    repo: angel539/extremo
