/**
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uam.extremo.casestudy.epmltext.ui.AbstractEPMLTextUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EPMLTextUiModule extends AbstractEPMLTextUiModule {
  public EPMLTextUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
