/**
 */
package semanticmanager.queries.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import semanticmanager.queries.util.QueriesAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class QueriesItemProviderAdapterFactory extends QueriesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public QueriesItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link semanticmanager.queries.SearchOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchOptionItemProvider searchOptionItemProvider;

	/**
	 * This creates an adapter for a {@link semanticmanager.queries.SearchOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchOptionAdapter() {
		if (searchOptionItemProvider == null) {
			searchOptionItemProvider = new SearchOptionItemProvider(this);
		}

		return searchOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link semanticmanager.queries.SearchResult} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchResultItemProvider searchResultItemProvider;

	/**
	 * This creates an adapter for a {@link semanticmanager.queries.SearchResult}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchResultAdapter() {
		if (searchResultItemProvider == null) {
			searchResultItemProvider = new SearchResultItemProvider(this);
		}

		return searchResultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link semanticmanager.queries.SearchResultOptionValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchResultOptionValueItemProvider searchResultOptionValueItemProvider;

	/**
	 * This creates an adapter for a {@link semanticmanager.queries.SearchResultOptionValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchResultOptionValueAdapter() {
		if (searchResultOptionValueItemProvider == null) {
			searchResultOptionValueItemProvider = new SearchResultOptionValueItemProvider(this);
		}

		return searchResultOptionValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link semanticmanager.queries.CompositeSearchConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeSearchConfigurationItemProvider compositeSearchConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link semanticmanager.queries.CompositeSearchConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeSearchConfigurationAdapter() {
		if (compositeSearchConfigurationItemProvider == null) {
			compositeSearchConfigurationItemProvider = new CompositeSearchConfigurationItemProvider(this);
		}

		return compositeSearchConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link semanticmanager.queries.CustomSearch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CustomSearchItemProvider customSearchItemProvider;

	/**
	 * This creates an adapter for a {@link semanticmanager.queries.CustomSearch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCustomSearchAdapter() {
		if (customSearchItemProvider == null) {
			customSearchItemProvider = new CustomSearchItemProvider(this);
		}

		return customSearchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link semanticmanager.queries.PredicateBasedSearch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PredicateBasedSearchItemProvider predicateBasedSearchItemProvider;

	/**
	 * This creates an adapter for a {@link semanticmanager.queries.PredicateBasedSearch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPredicateBasedSearchAdapter() {
		if (predicateBasedSearchItemProvider == null) {
			predicateBasedSearchItemProvider = new PredicateBasedSearchItemProvider(this);
		}

		return predicateBasedSearchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link semanticmanager.queries.SemanticGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticGroupItemProvider semanticGroupItemProvider;

	/**
	 * This creates an adapter for a {@link semanticmanager.queries.SemanticGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticGroupAdapter() {
		if (semanticGroupItemProvider == null) {
			semanticGroupItemProvider = new SemanticGroupItemProvider(this);
		}

		return semanticGroupItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (searchOptionItemProvider != null) searchOptionItemProvider.dispose();
		if (searchResultItemProvider != null) searchResultItemProvider.dispose();
		if (searchResultOptionValueItemProvider != null) searchResultOptionValueItemProvider.dispose();
		if (compositeSearchConfigurationItemProvider != null) compositeSearchConfigurationItemProvider.dispose();
		if (customSearchItemProvider != null) customSearchItemProvider.dispose();
		if (predicateBasedSearchItemProvider != null) predicateBasedSearchItemProvider.dispose();
		if (semanticGroupItemProvider != null) semanticGroupItemProvider.dispose();
	}

}
