/**
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.ui.contentassist;

import uam.extremo.casestudy.epmltext.ui.contentassist.AbstractEPMLTextProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EPMLTextProposalProvider extends AbstractEPMLTextProposalProvider {
}
