/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEPMLTextValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://angel539.github.io/extremo/casestudy/epml"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("urn:iso:std:iso:is:13584:-32:ed-1:tech:xml-schema:ontomlsimplified"));
		return result;
	}
	
}
