<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epml" nsURI="http://angel539.github.io/extremo/casestudy/epml"
    nsPrefix="epml">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAgents" upperBound="-1"
        eType="#//Agent" containment="true" eOpposite="#//Agent/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPlaces" upperBound="-1"
        eType="#//Place" containment="true" eOpposite="#//Place/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" abstract="true" eSuperTypes="eClassDictionary/eClassDictionary4.ecore#//CATEGORIZATIONCLASS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPorts" upperBound="-1"
        eType="#//Port" containment="true" eOpposite="#//Port/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Application"
        eOpposite="#//Application/ownedAgents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Agent"
        eOpposite="#//Agent/ownedPorts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="Place" abstract="true" eSuperTypes="eClassDictionary/eClassDictionary4.ecore#//CATEGORIZATIONCLASS #//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="matchRates"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="matchRates" value="if byteSize > 0 then byteSize >= itsOutputPort.byteRate and byteSize >= itsInputPort.byteRate else true endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itsOutputPort" lowerBound="1"
        eType="#//OutputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itsInputPort" lowerBound="1"
        eType="#//InputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Application"
        eOpposite="#//Application/ownedPlaces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCBasedControls" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fieldbus" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="RectangularConnectorSet" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="InductiveProximitySwitch" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationCable" eSuperTypes="#//Place"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReadyMadeDataCable" eSuperTypes="#//Place"/>
  <eClassifiers xsi:type="ecore:EClass" name="DCEngine" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="eClassDictionary/eClassDictionary4.ecore#//DICTIONARY #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedApplication" lowerBound="1"
        eType="#//Application" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
