/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uam.extremo.casestudy.epmltext.ui.internal.EpmltextActivator;

public class EPMLTextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EpmltextActivator.getInstance().getInjector("uam.extremo.casestudy.epmltext.EPMLText");
	}

}
