/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EPMLTextRuntimeModule extends AbstractEPMLTextRuntimeModule {
}
