/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EPMLTextStandaloneSetup extends EPMLTextStandaloneSetupGenerated {

	def static void doSetup() {
		new EPMLTextStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
