/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uam.extremo.casestudy.epmltext.parser.antlr.internal.InternalEPMLTextParser;
import uam.extremo.casestudy.epmltext.services.EPMLTextGrammarAccess;

public class EPMLTextParser extends AbstractAntlrParser {

	@Inject
	private EPMLTextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEPMLTextParser createParser(XtextTokenStream stream) {
		return new InternalEPMLTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}

	public EPMLTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EPMLTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
