/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EPMLTextAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uam/extremo/casestudy/epmltext/parser/antlr/internal/InternalEPMLText.tokens");
	}
}
