/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEPMLTextScopeProvider extends DelegatingScopeProvider {
}
