/**
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.ide;

import uam.extremo.casestudy.epmltext.ide.AbstractEPMLTextIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EPMLTextIdeModule extends AbstractEPMLTextIdeModule {
}
