<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="draggablesemanticmanager" nsURI="http://www.core.extremo/DraggableSemanticManager"
    nsPrefix="draggablesemanticmanager">
  <eClassifiers xsi:type="ecore:EClass" name="DraggableNamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptors" upperBound="-1"
        eType="#//DraggableNamedElement" eOpposite="#//DraggableNamedElement/describes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="describes" upperBound="-1"
        eType="#//DraggableNamedElement" eOpposite="#//DraggableNamedElement/descriptors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DraggableProperty" abstract="true" eSuperTypes="#//DraggableNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticNodeFrom" eType="#//DraggableSemanticNode"
        eOpposite="#//DraggableSemanticNode/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DraggableObjectProperty" eSuperTypes="#//DraggableProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//DraggableSemanticNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DraggableDataProperty" eSuperTypes="#//DraggableProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="DraggableSemanticNode" eSuperTypes="#//DraggableNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//DraggableProperty" containment="true" eOpposite="#//DraggableProperty/semanticNodeFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DraggableNamedElementSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="draggableSemanticNodes"
        upperBound="-1" eType="#//DraggableSemanticNode" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
