<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="main" nsURI="http://www.core.extremo/001/" nsPrefix="main">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bank" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transfer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="#//Frequency"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" eType="#//Account"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" eType="#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfer" eType="#//Transfer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bank" eType="#//Bank"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Account" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Swap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//Part"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" eType="#//Part"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListTasks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="swap" eType="#//Swap"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TaskType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Frequency">
    <eLiterals name="Yearly"/>
    <eLiterals name="Monthly" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskType">
    <eLiterals name="validate"/>
    <eLiterals name="package" value="1"/>
    <eLiterals name="verify" value="2"/>
  </eClassifiers>
</ecore:EPackage>
