<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="main" nsURI="http://www.core.extremo/002/" nsPrefix="main">
  <eClassifiers xsi:type="ecore:EClass" name="IRS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="swaps" upperBound="-1"
        eType="#//Swap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="companies" upperBound="-1"
        eType="#//Company" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bank" upperBound="-1" eType="#//Bank"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="execution" upperBound="-1"
        eType="#//Execution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Swap" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="legs" upperBound="2" eType="#//Leg"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leg" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfer" eType="#//Transfer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="company" eType="#//Company"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Company" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" upperBound="-1"
        eType="#//Account" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loan" upperBound="-1" eType="#//Loan"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transfer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="payment" eType="#//Period"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" eType="#//Account"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Period">
    <eLiterals name="MONTHLY"/>
    <eLiterals name="YEARLY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Account" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bank" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Execution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="swap" upperBound="-1" eType="#//Swap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bank" eType="#//Bank"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="payment" eType="#//Period"/>
  </eClassifiers>
</ecore:EPackage>
