<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="main" nsURI="http://www.core.extremo/007/" nsPrefix="main">
  <eClassifiers xsi:type="ecore:EClass" name="Bank" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Company" eSuperTypes="#//Bank"/>
  <eClassifiers xsi:type="ecore:EClass" name="Swap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Leg1" lowerBound="1" eType="#//Leg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Leg2" lowerBound="1" eType="#//Leg"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Facilitator" eType="#//Facilitator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Transfers" lowerBound="2"
        upperBound="4" eType="#//Transfer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Company" lowerBound="1"
        eType="#//Company"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bank" lowerBound="1" eType="#//Bank"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Transfer" lowerBound="1"
        eType="#//Transfer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transfer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sender" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Receiver" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//transferKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remaining amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Total Debt" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retention" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Facilitator" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EEnum" name="transferKinds">
    <eLiterals name="fixed"/>
    <eLiterals name="floatingEuribor" value="1"/>
    <eLiterals name="Other" value="2"/>
  </eClassifiers>
</ecore:EPackage>
