/**
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext;

import uam.extremo.casestudy.epmltext.EPMLTextStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EPMLTextStandaloneSetup extends EPMLTextStandaloneSetupGenerated {
  public static void doSetup() {
    new EPMLTextStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
