/**
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext;

import uam.extremo.casestudy.epmltext.AbstractEPMLTextRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EPMLTextRuntimeModule extends AbstractEPMLTextRuntimeModule {
}
