/*
 * generated by Xtext 2.12.0
 */
package uam.extremo.casestudy.epmltext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uam.extremo.casestudy.epmltext.ui.internal.EpmltextActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EPMLTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EpmltextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EpmltextActivator.getInstance().getInjector(EpmltextActivator.UAM_EXTREMO_CASESTUDY_EPMLTEXT_EPMLTEXT);
	}
	
}
